# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
env:
  global:
    - R_CHECK_ARGS="--no-vignettes --no-manual"
    - R_BUILD_ARGS="--no-vignettes"
